import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import { AiFillLinkedin} from 'react-icons/ai';
import {FaReact} from 'react-icons/fa';
import {FcPhoneAndroid} from 'react-icons/fc';
import {SiNextdotjs} from 'react-icons/si';
import { useState } from 'react';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);  

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Diego Portifolio </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-600 ">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
              <h1 className="text-xl font-burtons dark:text-white">
                D. Santana
              </h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill className="cursor-pointer text-2xl dark:text-white" onClick={() => setDarkMode(!darkMode)}/>
                </li>
                <li>
                  <a href="#" className="bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8">Resume</a>
                </li>
              </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Diego Santana</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Front End Developer 👾 </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              Hi everyone 
              <span className="animate-pulse">
              &nbsp; 👋🏻
              </span>
            </p>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              My name is Diego Santana and  I&apos;m Front End Developer. How can I help you at the your next project ?
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a target='_black' href='https://www.linkedin.com/in/diego-alves-santana-0720b317a/'>
            <AiFillLinkedin className='hover:fill-blue-700 hover:duration-200 hover:delay-200 dark:fill-white' />
            </a>            
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-200  rounded-full w-40 h-40 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover"/>
          </div>
        </section>

        <section className='sm:mx-auto sm:flex-col sm:flex sm:justify-center sm:items-center'>
          <article className="py-8">
            <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
          </article>  
          <div className="lg:flex gap-10 ">
            <article className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white ">
             <FaReact className='mx-auto h-24 fill-blue-700 w-24 animate-rotate' />
              <h3 className="text-lg font-medium pt-8 pb-2">Beatiful Designs</h3>
              <p>
                Creating elegant websites for something
              </p>
              <h4 className="py-4 text-teal-600">Web Framekworks tools I Use</h4>
              <p className="text-gray-800 py-1">React.Js</p>
            </article>
            <article className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white ">
              <SiNextdotjs className='mx-auto h-24 fill-grey-700 w-24 ' />

              <h3 className="text-lg font-medium pt-8 pb-2">Beatiful Designs</h3>
              <p>
                High performance using best technologies
              </p>
              <h4 className="py-4 text-teal-600">Framekworks tools I Use</h4>
              <p className="text-gray-800 py-1">Next.Js</p>
            </article>
            <article className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white ">
              <FcPhoneAndroid className='mx-auto h-24 w-24 animate-bounce' />
              <h3 className="text-lg font-medium pt-8 pb-2">Beatiful Designs</h3>
              <p>
                Creating elegant designs for mobile aplications
              </p>
              <h4 className="py-4 text-teal-600">Mobile Framekworks tools I Use</h4>
              <p className="text-gray-800 py-1">React Native</p>
            </article>
          </div>
        </section>
        <section>
          <article>
            <h3 className="text-3xl py-1 dark:text-white">Portifolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
            Since the beginning of my jorney as a freelancer developer, ve done remote work for
              <span className="text-teal-500">
              &nbsp;banks.
              </span>
            </p>
          </article>
          <article className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover ease-in duration-300 " width={'100%'} height={'100%'} layout={"responsive"}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout={"responsive"}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout={"responsive"}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout={"responsive"}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout={"responsive"}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout={"responsive"}/>
            </div>
          </article>
        </section>
      </main>
    </div>
  );
}
